name: ✨ Feature request
description: Suggest an idea for this project
title: "✨ "
labels: [✨ feature]
body:
  - type: textarea
    attributes:
      label: What feature or enhancement are you suggesting?
      description: Explain what the feature or enhancement is and why it's useful.
      placeholder: I think it would be great if create-nitro-project could support ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives/Workarounds
      description: Explain if there are any alternatives/workarounds.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Additional information
      description: Please check all the boxes that apply
      options:
        - label: I searched for [similar feature requests in this repository](https://github.com/margelo/create-nitro-project/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.
          required: true
